#!/bin/sh

#xclock -digital & 
#xsetroot -solid black &
#xli -onroot -quiet -fullscreen /home/fernando/imagens/16.jpg &
#tail -f /var/log/messages &
xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail &
